version: '3'
services:
  sentinel:
    container_name: sentinel-master
    image: redis:latest
    ports:
      - "26379:26379"
    restart: always
    volumes:
      - ./data:/data
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./log:/usr/local/etc/logs
    #command: bash -c "redis-server /usr/local/etc/redis/redis.conf && redis-sentinel /usr/local/etc/redis/sentinel.conf"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel1:
      container_name: sentinel-slave1
      image: redis:latest
      ports:
        - "26380:26379"
      restart: always
      volumes:
        - ./data1:/data
        - ./sentinel-slave1.conf:/usr/local/etc/redis/sentinel-slave1.conf
        - ./log1:/usr/local/etc/logs
      command: redis-sentinel /usr/local/etc/redis/sentinel-slave1.conf

      #command: bash -c "redis-server /usr/local/etc/redis/redis-slave1.conf && redis-sentinel /usr/local/etc/redis/sentinel-slave1.conf"


  sentinel2:
      container_name: sentinel-slave2
      image: redis:latest
      ports:
        - "26381:26379"
      restart: always
      volumes:
        - ./data2:/data
        - ./sentinel-slave2.conf:/usr/local/etc/redis/sentinel-slave2.conf
        - ./log2:/usr/local/etc/logs
      command: redis-sentinel /usr/local/etc/redis/sentinel-slave2.conf

      #command: bash -c "redis-server /usr/local/etc/redis/redis-slave2.conf && redis-sentinel /usr/local/etc/redis/sentinel-slave2.conf"

networks:
  default:
    external:
      name: redis_default
