apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    field.cattle.io/creatorId: user-mcq24
    field.cattle.io/publicEndpoints: '[{"addresses":["10.246.193.37"],"port":80,"protocol":"HTTP","serviceName":"production:ingress-c6dde88926ae045dec7aa4d68ba428a5","ingressName":"production:register","hostname":"register.production.10.246.193.37.xip.io","allNodes":true}]'
  creationTimestamp: "2019-09-14T07:28:41Z"
  generation: 12
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-production-eclb-register
  name: eclb-register
  namespace: production
  resourceVersion: "12675474"
  selfLink: /apis/apps/v1beta2/namespaces/production/deployments/eclb-register
  uid: 46bc8fdb-d6c1-11e9-a96f-0017fa030673
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-production-eclb-register
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-11-01T11:07:18Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-production-eclb-register
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - java -jar -Xms512m -Xmx1024m eureka-server.jar
        env:
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_DEFAULT_ZONE
          value: http://eclb-register:8000/eureka
        image: 139.217.219.149/cfs/eclb-register:master-20190914-065536
        imagePullPolicy: Always
        name: eclb-register
        resources:
          limits:
            memory: 1536Mi
          requests:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-09-14T07:30:20Z"
    lastUpdateTime: "2019-09-14T07:30:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-09-14T07:28:41Z"
    lastUpdateTime: "2019-11-01T11:07:29Z"
    message: ReplicaSet "eclb-register-7f74fdddbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
