apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "54"
    field.cattle.io/creatorId: user-mcq24
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"13","field.cattle.io/creatorId":"user-mcq24"},"creationTimestamp":null,"generation":1,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-production-eclb-service"},"name":"eclb-service","namespace":"production","selfLink":"/apis/apps/v1beta2/namespaces/production/deployments/eclb-service"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-production-eclb-service"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2019-09-19T03:50:06Z"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-production-eclb-service"}},"spec":{"containers":[{"command":["/bin/sh","-c","java
      -jar -Xms512m -Xmx1024m eclb-service.jar"],"env":[{"name":"CWS_HOSTURL","value":"https://cfsapi.ecolab.com.cn"},{"name":"CWS_REDIRECTURI","value":"/eclb/cws/redirect-url"},{"name":"ECLB_EXTRANET_FRONT","value":"https://cfs.ecolab.com.cn"},{"name":"ECLB_INTRANET_FRONT","value":"http://cfsIntranetuat.ecolab.com.cn"},{"name":"EUREKA_CLIENT_SERVICEURL_DEFAULTZONE","value":"http://eclb-register.production:8000/eureka/"},{"name":"FRONT_BASE_CONTXETPATH","value":"http://cfsIntranetuat.ecolab.com.cn"},{"name":"SPRING_CLOUD_CONFIG_ENABLED","value":"true"},{"name":"SPRING_CLOUD_CONFIG_URI","value":"http://eclb-config.production:8010/"},{"name":"SPRING_DATASOURCE_MAXIMUM_POOL_SIZE","value":"100"},{"name":"SPRING_DATASOURCE_PASSWORD","value":"CFSP@ssword#!"},{"name":"SPRING_DATASOURCE_URL","value":"jdbc:mysql://eclfincfsmysqlservere2001p.mysql.database.chinacloudapi.cn:3306/eclb_service?useUnicode=true\u0026characterEncoding=utf-8\u0026useSSL=false"},{"name":"SPRING_DATASOURCE_USERNAME","value":"CFSAdmin@eclfincfsmysqlservere2001p"},{"name":"SPRING_REDIS_HOST","value":"redis.production"}],"image":"139.217.219.149/cfs/eclb-service:master-20190919-112309","imagePullPolicy":"Always","name":"eclb-service","resources":{"limits":{"memory":"3Gi"},"requests":{"memory":"2Gi"}},"securityContext":{"allowPrivilegeEscalation":false,"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{}}'
  creationTimestamp: "2019-09-19T04:38:39Z"
  generation: 60
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-production-eclb-service
  name: eclb-service
  namespace: production
  resourceVersion: "116378025"
  selfLink: /apis/apps/v1beta2/namespaces/production/deployments/eclb-service
  uid: 59c2cc94-da97-11e9-9065-0017fa030673
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-production-eclb-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-12-24T13:29:34Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-production-eclb-service
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - java -jar -Xms512m -Xmx1024m eclb-service.jar
        env:
        - name: CWS_HOSTURL
          value: https://cfsapi.ecolab.com.cn
        - name: CWS_REDIRECTURI
          value: /eclb/cws/redirect-url
        - name: CWS_URL
          value: https://cwsapi.ecolab.com.cn
        - name: ECLB_EXTRANET_FRONT
          value: https://cfs.ecolab.com.cn/
        - name: ECLB_INTRANET_FRONT
          value: https://cfsweb.ecolab.com.cn/
        - name: EMAIL_SERVER_CODE
          value: CFS
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eclb-register.production:8000/eureka/
        - name: HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS
          value: "61000"
        - name: RIBBON_READ_TIMEOUT
          value: "60000"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "true"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://eclb-config.production:8010/
        - name: SPRING_DATASOURCE_MAXIMUM_POOL_SIZE
          value: "80"
        - name: SPRING_DATASOURCE_PASSWORD
          value: CFSP@ssword#!
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://eclfincfsmysqlservere2001p.mysql.database.chinacloudapi.cn:3306/eclb_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: CFSAdmin@eclfincfsmysqlservere2001p
        - name: SPRING_REDIS_HOST
          value: 10.246.193.252
        - name: SPRING_REDIS_PASSWORD
          value: ai9+xehAHl2HfdrqTXN6rLgoIeD1L8tqHyaUhTlvR3w=
        image: 139.217.219.149/prod/eclb-service:master-20201224-174328
        imagePullPolicy: Always
        name: eclb-service
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-08-12T00:41:07Z"
    lastUpdateTime: "2020-08-12T00:41:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-10-10T14:29:23Z"
    lastUpdateTime: "2020-12-24T13:31:39Z"
    message: ReplicaSet "eclb-service-59f6db77d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 60
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
