spring:
  application:
    name: hzl-register
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  freemarker:
      # 禁用模板缓存
      cache: false
      # 编码格式
      charset: UTF-8
      # freemarker模板后缀 默认是 .ftl
      suffix: .html
      # 是否为此技术启用MVC视图分辨率。
      enabled: true
      # Content-Type值
      content-type: text/html
      # #模板加载路径 按需配置 ,默认路径是 classpath:/templates/
      template-loader-path: classpath:/templates/
  #开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
  #邮件配置信息，后期可保存到数据库
  mail:
    host: hwhzsmtp.qiye.163.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cache:
    type: redis #设置cache的类型,none是禁用cache缓存
  redis:
    host: localhost
    port: 6379

  #mysql连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hcbm_contract?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
          username: ${SPRING_DATASOURCE_USERNAME:hcbm}
          password: ${SPRING_DATASOURCE_PASSWORD:hcbm}
          initial-size: 5  # 初始化大小
          min-idle: 5  # 最小
          max-active: 100  # 最大
          max-wait: 60000  # 配置获取连接等待超时的时间
          time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
          validationQuery: select 'x'
          test-while-idle: true  # 当连接空闲时，是否执行连接测试
          test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接 建议关闭，影响性能
          test-on-return: false  # 在连接归还到连接池时是否测试该连接 建议关闭，影响性能
          filters: config,wall,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          poolPreparedStatements: false   #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
          maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
          maxOpenPreparedStatements: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: 'druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;config.decrypt=false'

    slave1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.200.254.56:3306/hcbm_contract?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
          username: ${SPRING_DATASOURCE_USERNAME:hcbm}
          password: ${SPRING_DATASOURCE_PASSWORD:hcbm}
          initial-size: 5  # 初始化大小
          min-idle: 5  # 最小
          max-active: 100  # 最大
          max-wait: 60000  # 配置获取连接等待超时的时间
          time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
          validationQuery: select 'x'
          test-while-idle: true  # 当连接空闲时，是否执行连接测试
          test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接 建议关闭，影响性能
          test-on-return: false  # 在连接归还到连接池时是否测试该连接 建议关闭，影响性能
          filters: config,wall,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          poolPreparedStatements: false   #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
          maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
          maxOpenPreparedStatements: 20
           # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: 'druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;config.decrypt=false'

#后期这部分可以改造成java类配置
    druid:
     # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: false
      #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
          enabled: true #是否启用StatFilter默认值true
          url-pattern: /*
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
          session-stat-enable: true
          session-stat-max-count: 10
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
          enabled: true #是否启用StatViewServlet默认值true
          url-pattern: /druid/*
          reset-enable: true
          login-username: admin
          login-password: admin
      db-type: mysql

  jpa:
    show-sql: true


ribbon:
  nacos:
    enabled: true

# 包扫描或者在启动类上添加@MapperScan或者在每个mapper接口上添加@Mapper注解
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
    cache-enabled: false #关闭二级缓存

#日志springboot默认日志logback，默认等级为info
logging:
  level:
    #root: debug 所有目录的日志等级都为debug
    org.hzero: debug #指定目录下的日志，等级为debug
  config: 'classpath:logback-spring.xml'

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#tk插件配置
mapper:
  identity: mysql
  mappers:
      - com.hzl.hadoop.config.mybatis.BaseMapperUtil
  not-empty: false



---

spring:
  profiles: local  # 本地开发