spring:
  application:
    name: hzl-register
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  freemarker:
      # 禁用模板缓存
      cache: false
      # 编码格式
      charset: UTF-8
      # freemarker模板后缀 默认是 .ftl
      suffix: .html
      # 是否为此技术启用MVC视图分辨率。
      enabled: true
      # Content-Type值
      content-type: text/html
      # #模板加载路径 按需配置 ,默认路径是 classpath:/templates/
      template-loader-path: classpath:/templates/
  #邮件配置信息，后期可保存到数据库
  mail:
    host:
    username: 1620516418@qq.com
    password:
    protocol: smtp
ribbon:
  nacos:
    enabled: true