version: '3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data:/usr/share/filebeat/data
      - /Users/hzl/Desktop/hadoopcloud/hadoop-cloud-register/logs:/var/log/test911/
    restart: always
