version: '3'
services:
  fluentd:
    image: fluent:local
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ../logs:/fluentd/logs
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"
    restart: always

  elasticsearch:
    image: elasticsearch:6.8.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ./data:/path/to/data
      - ./logs:/path/to/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:6.8.2
    container_name: kibana
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: always