version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:7.6.0
    container_name: kibana
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: always