version: '3'
services:
  hadoop:
    container_name: hadoopnamenode
    image: registry.cn-hangzhou.aliyuncs.com/hzl-hadoop/hzl:register-0.0.02
    user: root
    ports:
        - "8888:8888"
#    volumes:
#        - ./target/hadoop.jar:~/
#        - ./logs/:~/
#    command: sh ~/start.sh
#    restart: always
    network_mode: "host"
