version: '3'
services:
  logstash:
    container_name: logstash
    image: logstash:7.6.0
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/:/usr/share/logstash/config/
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ${PWD}/logs:/user/share/logs
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
          LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    restart: always

