version: '3'
services:
  hadoop:
    container_name: hadoopnamenode
    image: hadoop:1.0
    user: root
    restart: always

  hadoop1:
    container_name: hadoopdatanode1
    image: hadoop:1.0
    user: root
    restart: always

  hadoop2:
    container_name: hadoopdatanode2
    image: hadoop:1.0
    user: root
    restart: always