version: '3'
services:
  redis:
    container_name: redis-master
    image: redis:latest
    ports:
     - "6379:6379"
    restart: always
    volumes:
    - ./data:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf